version: 2
updates:
- package-ecosystem: "gitsubmodule"
  directory: "/"
  schedule:
    interval: "daily"
  groups:
    submodules:
      dependency-type: "production"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
